lobbyLocation: 'world:-201:71:264:4:21'
isEditMode: true
signs: ''
game:
  normalItems:
    - STONE
    - GRASS
    - DIRT
    - COBBLESTONE
    - WOOD
    - SAND
    - SPONGE
    - GLASS
    - LAPIS_BLOCK
    - WEB
    - WOOL
    - BRICK
    - TORCH
    - LADDER
    - SLIME_BLOCK
    - IRON_SPADE
    - IRON_PICKAXE
    - IRON_AXE
    - FLINT_AND_STEEL
    - APPLE
    - BOW
    - COAL
    - GOLD_INGOT
    - WOOD_SWORD
    - STONE_SWORD
    - STONE_AXE
    - STICK
    - SEEDS
    - BREAD
    - LEATHER_HELMET
    - LEATHER_CHESTPLATE
    - LEATHER_LEGGINGS
    - LEATHER_BOOTS
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - IRON_CHESTPLATE
    - CHAINMAIL_BOOTS
    - GOLD_HELMET
    - GOLD_CHESTPLATE
    - GOLD_LEGGINGS
    - GOLD_BOOTS
    - PORK
    - BOAT
    - LEATHER
    - MILK_BUCKET
    - EGG
    - COMPASS
  rareItems:
    - WATER_BUCKET
    - LAVA_BUCKET
    - SNOW_BALL
    - BOAT
    - LEATHER
    - MILK_BUCKET
    - CHAINMAIL_HELMET
    - CHAINMAIL_CHESTPLATE
    - CHAINMAIL_LEGGINGS
    - CHAINMAIL_BOOTS
    - IRON_HELMET
    - IRON_CHESTPLATE
    - IRON_LEGGINGS
    - IRON_BOOTS
  legendaryItems:
    - DIAMOND_HELMET
    - DIAMOND_CHESTPLATE
    - DIAMOND_LEGGINGS
    - DIAMOND_BOOTS
    - GOLD_HELMET
    - GOLD_CHESTPLATE
    - GOLD_LEGGINGS
    - GOLD_BOOTS
    - GOLD_RECORD
    - GREEN_RECORD
    - QUARTZ
    - RECORD_3
    - RECORD_4
    - RECORD_5
    - RECORD_6
    - RECORD_7
    - RECORD_8
    - RECORD_9
    - RECORD_10
    - RECORD_11
    - RECORD_12